import type { ProgramaImportPayload } from '@/lib/programa-import'

/** Programa Virgen de la Asunción — Parroquia Z2 + coords aproximadas Centro Histórico */
export const PRESET_VIRGEN_ASUNCION: ProgramaImportPayload = {
  nombre: 'Virgen de la Asunción',
  turnos: [
    {
      label: 'Honor Salida',
      direccion: 'Del interior del templo a la 5ta. calle sobre la 7ma. avenida zona 2',
      tipo: 'ida',
      lat: 14.64993,
      lng: -90.51049,
      piezas: [
        { nombre: 'Himno a la Asunción', autor: 'José Cubeles / Arr. Luis Pirir' },
        { nombre: 'Las Tortugas', autor: 'José Cupertino' },
        { nombre: 'La Granadera', autor: 'D.R.A' },
        { nombre: 'Manzanilla', autor: 'Rafael Juárez Toledo' },
        { nombre: 'Neblina', autor: 'José Domingo Velásquez' },
      ],
    },
    {
      label: 'Turno 2',
      direccion: 'De la 5ta. calle a la 4ta. calle sobre la 7ma. avenida zona 2',
      tipo: 'ida',
      lat: 14.64982,
      lng: -90.51049,
      piezas: [
        { nombre: 'Najij Noj', autor: 'Nazario Rucal' },
      ],
    },
    {
      label: 'Turno 3',
      direccion: 'De la 7ma. avenida a la 8va. avenida sobre la 4ta. calle zona 2',
      tipo: 'ida',
      lat: 14.648963,
      lng: -90.51049,
      piezas: [
        { nombre: 'El Gato Montes', autor: 'Manuel Penella Moreno' },
      ],
    },
    {
      label: 'Turno 4',
      direccion: 'De la 4ta. calle a la 3era. calle sobre la 8va. avenida zona 2',
      tipo: 'ida',
      lat: 14.648963,
      lng: -90.509176,
      piezas: [
        { nombre: 'El Enfrascade', autor: 'José De León' },
      ],
    },
    {
      label: 'Turno 5',
      direccion: 'De 8va. avenida a la 7ma. avenida sobre la 3era. calle de la zona 2',
      tipo: 'ida',
      lat: 14.648106,
      lng: -90.509176,
      piezas: [
        { nombre: 'El Jute', autor: 'Alfredo Dávila Rendón' },
      ],
    },
    {
      label: 'Turno 6',
      direccion: 'De la 3era. calle a la 2da. calle sobre la 7ma. avenida zona 2',
      tipo: 'ida',
      lat: 14.648106,
      lng: -90.51049,
      piezas: [
        { nombre: 'Patzún de mis recuerdos', autor: 'Reginaldo Melgar' },
      ],
    },
    {
      label: 'Turno 7',
      direccion: 'De la 2da. calle a la 1era. calle sobre la 7ma. avenida zona 2',
      tipo: 'ida',
      lat: 14.647249,
      lng: -90.51049,
      piezas: [
        { nombre: 'El Poder del amor', autor: 'Mons. Joaquín Santa María y Vigil' },
      ],
    },
    {
      label: 'Turno 8',
      direccion: 'De la 1era. calle zona 2 a la 1era. calle zona 1 sobre la 7ma. avenida zona 2',
      tipo: 'ida',
      lat: 14.646392,
      lng: -90.51049,
      piezas: [
        { nombre: 'El Buey y la Mula', autor: 'Federico García' },
        { nombre: 'A Orillas del Panajachel', autor: 'Everardo De León' },
      ],
    },
    {
      label: 'Turno 9',
      direccion: 'De la 1era. calle a la 2da. calle sobre la 7ma. avenida zona 1',
      tipo: 'ida',
      lat: 14.646092,
      lng: -90.51275,
      piezas: [
        { nombre: 'Mi bella Guatemala', autor: 'German Alcántara' },
      ],
    },
    {
      label: 'Turno 10',
      direccion: 'De la 7ma. avenida a la 6ta. avenida sobre la 2da. calle de la zona 1',
      tipo: 'ida',
      lat: 14.645235,
      lng: -90.51275,
      piezas: [
        { nombre: 'Barras y Estrellas', autor: 'John Philip Sousa' },
        { nombre: 'Mi linda María', autor: 'Adrian Tzul' },
      ],
    },
    {
      label: 'Turno 11',
      direccion: 'De la 6ta. avenida a la 5ta. avenida sobre la 2da. calle zona 1',
      tipo: 'ida',
      lat: 14.645235,
      lng: -90.514064,
      piezas: [
        { nombre: 'La Sandunga', autor: 'Máximo Ramón Ortiz' },
      ],
    },
    {
      label: 'Turno 12',
      direccion: 'De la 5ta. avenida a la 4ta. avenida sobre la 2da. calle zona 1',
      tipo: 'ida',
      lat: 14.645235,
      lng: -90.515378,
      piezas: [
        { nombre: 'Salve Emperatriz de America', autor: 'Carlos Echigoyen' },
      ],
    },
    {
      label: 'Turno 13',
      direccion: 'De la 4ta. avenida a la 3era. avenida sobre la 2da. calle zona 1',
      tipo: 'ida',
      lat: 14.645235,
      lng: -90.516693,
      piezas: [
        { nombre: 'Llegarás a Quererme', autor: 'Salomón Argueta' },
        { nombre: 'España Cañí', autor: 'Pascual Marquina Narro' },
      ],
    },
    {
      label: 'Turno 14',
      direccion: 'De la 2da. calle a la 3era. calle sobre la 3era. avenida zona 1',
      tipo: 'ida',
      lat: 14.645235,
      lng: -90.518007,
      piezas: [
        { nombre: 'Sal Negra', autor: 'Juan Hernández' },
        { nombre: 'Ave María', autor: 'Fray Miguel Murcia' },
      ],
    },
    {
      label: 'Turno 15',
      direccion: 'De la 3era. avenida a la 4ta. avenida sobre la 3era. calle zona 1',
      tipo: 'ida',
      lat: 14.644378,
      lng: -90.518007,
      piezas: [
        { nombre: 'Añoranzas', autor: 'Wotzbelí Aguilar' },
        { nombre: 'Asunción Bendita', autor: 'Cristian González Ajín' },
      ],
    },
    {
      label: 'Turno 16',
      direccion: 'De la 4ta. avenida a la 5ta. avenida sobre la 3era. calle zona 1',
      tipo: 'ida',
      lat: 14.644378,
      lng: -90.516693,
      piezas: [
        { nombre: 'Nereidas', autor: 'Amador Pérez' },
      ],
    },
    {
      label: 'Turno 17',
      direccion: 'De la 3era. calle a la 4ta. calle sobre la 5ta. avenida zona 1',
      tipo: 'ida',
      lat: 14.644378,
      lng: -90.515378,
      piezas: [
        { nombre: 'Quincho Barrilete', autor: 'Carlos Mejía Godoy' },
        { nombre: 'Rio Polochic', autor: 'Rodolfo Chavarria' },
      ],
    },
    {
      label: 'Turno 18',
      direccion: 'De la 4ta. calle a la 5ta. calle sobre la 5ta. avenida zona 1',
      tipo: 'ida',
      lat: 14.643521,
      lng: -90.515378,
      piezas: [
        { nombre: 'El Pavo Real', autor: 'Julio Anibal Delgado' },
        { nombre: 'Santiaguito', autor: 'Domingo Bethancourt' },
      ],
    },
    {
      label: 'Turno 19',
      direccion: 'De la 5ta. avenida a la 6ta. avenida sobre la 5ta. calle zona 1',
      tipo: 'ida',
      lat: 14.642664,
      lng: -90.515378,
      piezas: [
        { nombre: 'El Rey Quiche', autor: 'Daniel Hurtado' },
      ],
    },
    {
      label: 'Turno 20',
      direccion: 'De la 6ta. avenida a la 7ma. avenida sobre la 5ta. calle zona 1',
      tipo: 'ida',
      lat: 14.642664,
      lng: -90.514064,
      piezas: [
        { nombre: 'Callejuela de la O', autor: 'Paco Lola' },
        { nombre: 'La Virgen de la Feria', autor: 'Samuel Pascual' },
      ],
    },
    {
      label: 'Turno 21',
      direccion: 'De la 5ta. calle a la 6ta. calle sobre la 7ma. avenida zona 1',
      tipo: 'ida',
      lat: 14.642664,
      lng: -90.51275,
      piezas: [
        { nombre: 'Salve Rociera', autor: 'Manuel Pareja Obregón' },
      ],
    },
    {
      label: 'Honor Entrada Catedral',
      direccion: 'De la 6ª calle y 7ª avenida al interior de la Catedral',
      tipo: 'ida',
      lat: 14.641483,
      lng: -90.512046,
      piezas: [
        { nombre: 'El Grito', autor: 'José Ernesto Monzón' },
        { nombre: 'Granadera', autor: 'Ramón González' },
        { nombre: 'Ixtia Chimalteca', autor: 'Felipe Ávila' },
        { nombre: 'Ave María', autor: 'Giulio Caccini' },
      ],
    },
    {
      label: 'Honor Salida Catedral',
      direccion: 'Del interior de la Catedral a la 7ª avenida y 8ª calle, zona 1',
      tipo: 'ida',
      lat: 14.640093,
      lng: -90.51275,
      piezas: [
        { nombre: 'Himno de la Asunción', autor: 'José Cubeles/Arr. Luis Pirir' },
        { nombre: 'La Sanjuanerita', autor: 'José Ernesto Monzón' },
        { nombre: 'Granadera', autor: 'Ramón González' },
        { nombre: 'El Costumbro', autor: 'Disiderio Gallardo Ruiz' },
      ],
    },
    {
      label: 'Extraordinario Portal del Comercio',
      direccion: 'De la 7ª avenida a la 6ª avenida sobre la 8ª calle, zona 1',
      tipo: 'ida',
      lat: 14.640093,
      lng: -90.514064,
      piezas: [
        { nombre: 'Ave María', autor: 'Franz Schubert' },
        { nombre: 'El Jilguero', autor: 'Juan Hernández' },
      ],
    },
    {
      label: 'Turno 25',
      direccion: 'De la 8ª a la 9ª calle sobre la 6ª avenida zona 1',
      tipo: 'ida',
      lat: 14.639236,
      lng: -90.514064,
      piezas: [
        { nombre: 'La Esperanza de María', autor: 'Alejandro Blanco' },
        { nombre: '¡Reina!', autor: 'José Miguel López Rueda' },
      ],
    },
    {
      label: 'Turno 26',
      direccion: 'De la 9ª a la 10ª calle sobre la 6ª avenida zona 1',
      tipo: 'ida',
      lat: 14.638379,
      lng: -90.514064,
      piezas: [
        { nombre: 'Tennis Club', autor: 'Rocael Hurtado' },
      ],
    },
    {
      label: 'Turno 27',
      direccion: 'De la 10ª a la 11ª calle sobre la 6ª avenida zona 1',
      tipo: 'ida',
      lat: 14.637522,
      lng: -90.514064,
      piezas: [
        { nombre: 'Linda Shecanita', autor: 'Alejandro Orozco' },
        { nombre: 'La Cofradía de San Pedro', autor: 'Arr. Samuel Pascual' },
      ],
    },
    {
      label: 'Turno 28',
      direccion: 'De la 11 a la 12 calle sobre la 6ª avenida zona 1',
      tipo: 'ida',
      lat: 14.636665,
      lng: -90.514064,
      piezas: [
        { nombre: 'Coty Diaz', autor: 'Raymundo Díaz Rivera' },
      ],
    },
    {
      label: 'Turno 29',
      direccion: 'De la 12 calle a la 13 calle sobre la 6ª avenida zona 1',
      tipo: 'ida',
      lat: 14.635763,
      lng: -90.514064,
      piezas: [
        { nombre: 'Martin Cola', autor: 'Victor Manuel Lara' },
      ],
    },
    {
      label: 'Extraordinario San Francisco',
      direccion: 'De la 6ta. avenida y 13 calle al portico principal del Templo de San Francisco',
      tipo: 'ida',
      lat: 14.635763,
      lng: -90.51275,
      piezas: [
        { nombre: 'San Francisco de Asís', autor: 'Froilán Rodas' },
        { nombre: 'La Granadera', autor: 'D.R.A' },
        { nombre: 'Pues Concebida', autor: 'Canto Popular' },
      ],
    },
    {
      label: 'Turno 31',
      direccion: 'De la 6ta. avenida a la 7ma. avenida sobre la 13 calle zona 1',
      tipo: 'ida',
      lat: 14.636665,
      lng: -90.51275,
      piezas: [
        { nombre: 'Cofradía de la Inmaculada Concepción', autor: 'Samuel Pascual' },
        { nombre: 'El Sembrador', autor: 'Lester Homero Godínez' },
      ],
    },
    {
      label: 'Turno 32',
      direccion: 'De la 13 calle a la 12 calle sobre la 7ª avenida, zona 1',
      tipo: 'ida',
      lat: 14.636665,
      lng: -90.511435,
      piezas: [
        { nombre: 'Nos Amaremos en Abril', autor: 'Marco Antonio Barrios' },
      ],
    },
    {
      label: 'Extraordinario Arco de Correos',
      direccion: 'De la 7ª a la 8ª avenida sobre la 12 calle zona 1',
      tipo: 'ida',
      lat: 14.636665,
      lng: -90.510121,
      piezas: [
        { nombre: 'La Quema del Diablo', autor: 'Rafael Juárez Toledo' },
        { nombre: 'Un vals para la Reina del Cielo', autor: 'Luis Pirir' },
      ],
    },
    {
      label: 'Turno 34',
      direccion: 'De la 8ª a la 9ª avenida sobre la 12 calle zona 1',
      tipo: 'ida',
      lat: 14.636665,
      lng: -90.508806,
      piezas: [
        { nombre: 'El Carbonero', autor: 'Francisco Lara' },
      ],
    },
    {
      label: 'Turno 35',
      direccion: 'De la 9ª a la 10ª avenida sobre la 12 calle zona 1',
      tipo: 'ida',
      lat: 14.636665,
      lng: -90.507492,
      piezas: [
        { nombre: 'Cunen en fiesta', autor: 'Rafael Ibarra Ávila' },
      ],
    },
    {
      label: 'Turno 36',
      direccion: 'De la 10ª a la 11ª avenida sobre la 12 calle zona 1',
      tipo: 'ida',
      lat: 14.636665,
      lng: -90.506178,
      piezas: [
        { nombre: 'Flor del Café', autor: 'Germán Alcántara' },
      ],
    },
    {
      label: 'Turno 37',
      direccion: 'De la 11 a la 12 avenida sobre la 12 calle zona 1',
      tipo: 'ida',
      lat: 14.637522,
      lng: -90.506178,
      piezas: [
        { nombre: 'Sobre las olas', autor: 'Juventino Rosas' },
      ],
    },
    {
      label: 'Turno 38',
      direccion: 'De la 12 a la 11 calle sobre la 12 avenida zona 1',
      tipo: 'regreso',
      lat: 14.637522,
      lng: -90.506178,
      piezas: [
        { nombre: 'Reina y Madre', autor: 'Waldir Edinilson Contreras Pedroza' },
      ],
    },
    {
      label: 'Extraordinario Santo Domingo',
      direccion: 'De la 11 calle al atrio del templo de Santo Domingo sobre la 12 avenida zona 1',
      tipo: 'regreso',
      lat: 14.638379,
      lng: -90.506178,
      piezas: [
        { nombre: 'El Cacique Dormido', autor: 'Domingo Bethancourt' },
        { nombre: 'El Niño del Santisimo', autor: 'Raymundo Díaz' },
        { nombre: 'Himno al Rosario', autor: 'Fray María Francisco' },
        { nombre: 'La Granadera', autor: 'D.R.A' },
      ],
    },
    {
      label: 'Turno 40',
      direccion: 'Del atrio del Templo de Santo Domingo a la 10ma. calle sobre la 12 avenida zona 1',
      tipo: 'regreso',
      lat: 14.638379,
      lng: -90.507492,
      piezas: [
        { nombre: 'Himno a la Coronación Pontificia', autor: 'Miguel Zaltrón' },
        { nombre: 'Santo Domingo de Guzmán', autor: 'Wilver Hernandez' },
      ],
    },
    {
      label: 'Turno 41',
      direccion: 'De la 12 avenida a la 11 avenida sobre la 10ma. calle zona 1',
      tipo: 'regreso',
      lat: 14.639236,
      lng: -90.507492,
      piezas: [
        { nombre: 'La Feria de las Flores', autor: 'Jesús Monge' },
        { nombre: 'Migdalia Azucena', autor: 'Gumercindo Palacios' },
      ],
    },
    {
      label: 'Turno 42',
      direccion: 'De la 10ma. calle a la 9na. calle sobre la 11 avenida zona 1',
      tipo: 'regreso',
      lat: 14.639871,
      lng: -90.507755,
      piezas: [
        { nombre: 'San José Carpintero, Carpintero.', autor: 'Samuel Pascual' },
        { nombre: 'La Danza de los Venados', autor: 'Rafael Juárez Toledo' },
      ],
    },
    {
      label: 'Extraordinario Parque Colón',
      direccion: 'De la 9na. calle a la 8va. calle sobre la 11 avenida zona 1',
      tipo: 'regreso',
      lat: 14.64095,
      lng: -90.507492,
      piezas: [
        { nombre: 'La Quebrada', autor: 'Lester Godínez' },
        { nombre: 'Maricumbia', autor: 'Julio Anibal Delgado' },
      ],
    },
    {
      label: 'Turno 44',
      direccion: 'De la 8va. calle a la 7ma. calle sobre la 11 avenida, zona 1',
      tipo: 'regreso',
      lat: 14.642677,
      lng: -90.507492,
      piezas: [
        { nombre: 'Son de la Patroncita', autor: 'Wilver Hernandez' },
      ],
    },
    {
      label: 'Turno 45',
      direccion: 'De la 7ma. calle a la 5ta. calle sobre 11 avenida zona 1',
      tipo: 'regreso',
      lat: 14.643521,
      lng: -90.507492,
      piezas: [
        { nombre: 'Las Chiapanecas', autor: 'Bulmaro López' },
        { nombre: 'Dogma', autor: 'Yarol Cur / Arr. Samuel Pascual' },
      ],
    },
    {
      label: 'Extraordinario La Merced',
      direccion: 'De la 5ª calle a la 4ª calle sobre la 11 avenida zona 1',
      tipo: 'regreso',
      lat: 14.643521,
      lng: -90.508806,
      piezas: [
        { nombre: 'Caridad de Guadalquivir', autor: 'Paco Lola' },
        { nombre: 'Lain Nebaj', autor: 'Rafael Juárez Toledo' },
      ],
    },
    {
      label: 'Turno 47',
      direccion: 'De la 11 avenida a la 10ma. avenida sobre la 4ta. calle zona 1',
      tipo: 'regreso',
      lat: 14.643521,
      lng: -90.510121,
      piezas: [
        { nombre: 'El Danubio Azul', autor: 'Johann Strauss' },
        { nombre: 'Inmaculada Virgen María', autor: 'Hector Gómez Barillas' },
      ],
    },
    {
      label: 'Turno 48',
      direccion: 'De la 10ma. avenida a la 9na. avenida sobre la 4ta. calle zona 1',
      tipo: 'regreso',
      lat: 14.644483,
      lng: -90.51051,
      piezas: [
        { nombre: 'Cuando el indio llora', autor: 'José María Mejía' },
      ],
    },
    {
      label: 'Extraordinario Santa Teresa',
      direccion: 'De la 9na. avenida a la 8va. avenida sobre la 4ta. calle zona 1',
      tipo: 'regreso',
      lat: 14.642664,
      lng: -90.511435,
      piezas: [
        { nombre: 'Virgen del Carmen', autor: 'Byron Santizo' },
        { nombre: 'Tsio Ti', autor: 'Lester Godínez' },
      ],
    },
    {
      label: 'Turno 50',
      direccion: 'De la 4ta. calle a la 5ta. calle sobre la 8va. avenida zona 1',
      tipo: 'regreso',
      lat: 14.641807,
      lng: -90.511435,
      piezas: [
        { nombre: 'Recuerdos de un amigo', autor: 'Belarmino Molina' },
      ],
    },
    {
      label: 'Turno 51',
      direccion: 'De la 5ta. calle a la 6ta. calle sobre la 8va. avenida zona 1',
      tipo: 'regreso',
      lat: 14.641807,
      lng: -90.51275,
      piezas: [
        { nombre: 'Hermosa Doncella', autor: 'Luciano Jimenez' },
      ],
    },
    {
      label: 'Turno 52',
      direccion: 'De la 8va. avenida a la 7ma. avenida sobre la 6ta. calle zona 1',
      tipo: 'regreso',
      lat: 14.642919,
      lng: -90.513067,
      piezas: [
        { nombre: 'Ferrocarril de los Altos', autor: 'Domingo Bethancourt' },
        { nombre: 'Maria Luisa I', autor: 'Enrique Castro' },
      ],
    },
    {
      label: 'Palacio Nacional',
      direccion: 'De la 7ma. avenida a la 6ta. avenida sobre la 6ta. calle zona 1',
      tipo: 'regreso',
      lat: 14.642664,
      lng: -90.514064,
      piezas: [
        { nombre: 'El Sembrador', autor: 'Lester Homero Godínez' },
        { nombre: 'La Gloria del Pueblo', autor: 'Felix de Carboneras' },
      ],
    },
    {
      label: 'Turno 54',
      direccion: 'De la 6ta. calle a la 5ta. calle sobre la 6ta. avenida zona 1',
      tipo: 'regreso',
      lat: 14.643521,
      lng: -90.514064,
      piezas: [
        { nombre: 'La caída del Sol', autor: 'Santiago Cruz' },
      ],
    },
    {
      label: 'Turno 55',
      direccion: 'De la 5ta. calle a la 4ta. calle sobre la 6ta. avenida de la zona 1',
      tipo: 'regreso',
      lat: 14.644378,
      lng: -90.514064,
      piezas: [
        { nombre: 'Golosinas de Amatitlan', autor: 'Carlos Morales' },
        { nombre: 'Inmaculada Virgen María', autor: 'Hector Gómez Barillas' },
      ],
    },
    {
      label: 'Turno 56',
      direccion: 'De la 4ta. calle a la 3era. calle sobre la 6ta. avenida zona 1',
      tipo: 'regreso',
      lat: 14.646192,
      lng: -90.512585,
      piezas: [
        { nombre: 'Mi Catochita', autor: 'Manolo Fernandez' },
        { nombre: 'La Patrona de mi pueblo', autor: 'Carlos Alfonso Colindres' },
      ],
    },
    {
      label: 'Extraordinario San Sebastián',
      direccion: 'De la 3ra. calle a la 2da. calle sobre la 6ta. avenida de la zona 1',
      tipo: 'regreso',
      lat: 14.646392,
      lng: -90.514064,
      piezas: [
        { nombre: 'Herencia de Abuelos', autor: 'Oscar Ajín' },
        { nombre: 'La Chirimía', autor: 'Alejandro Orozco' },
      ],
    },
    {
      label: 'Turno 58',
      direccion: 'De la 2da. calle zona 1 a la 1era. calle zona 2 sobre la 6ta. avenida',
      tipo: 'regreso',
      lat: 14.647249,
      lng: -90.514064,
      piezas: [
        { nombre: 'Virgen de Morenos', autor: 'Luis Ortiz' },
        { nombre: 'Luna de Xelaju', autor: 'Francisco Pérez' },
      ],
    },
    {
      label: 'Turno 59',
      direccion: 'De la 1era. calle a la 2da calle sobre la 6ta. avenida zona 2',
      tipo: 'regreso',
      lat: 14.647249,
      lng: -90.515378,
      piezas: [
        { nombre: 'Ave María', autor: 'William Gómez' },
      ],
    },
    {
      label: 'Turno 60',
      direccion: 'De la 6ta. avenida a la 5ta. avenida sobre la 2da. calle zona 2',
      tipo: 'regreso',
      lat: 14.648106,
      lng: -90.515378,
      piezas: [
        { nombre: 'Danzón', autor: 'Belarmino Molina' },
        { nombre: 'San Bartolo', autor: 'Gabriel Hurtado' },
      ],
    },
    {
      label: 'Turno 61',
      direccion: 'De la 2da. calle a la 3era. calle sobre la 5ta. avenida zona 2',
      tipo: 'regreso',
      lat: 14.648963,
      lng: -90.515378,
      piezas: [
        { nombre: 'Noches de Escuintla', autor: 'María del Tránsito Barrios' },
        { nombre: 'Callecitas de San Marcos', autor: 'Carlos Enrique Arango' },
      ],
    },
    {
      label: 'Turno 62',
      direccion: 'De la 3era. calle a la 4ta. calle sobre la 5ta. avenida zona 2',
      tipo: 'regreso',
      lat: 14.64982,
      lng: -90.515378,
      piezas: [
        { nombre: 'Un día de amor', autor: 'José María Girón' },
        { nombre: 'Santo Domingo Xenacoj', autor: 'Elpidio Cano' },
      ],
    },
    {
      label: 'Turno 63',
      direccion: 'De la 4ta. calle a la 5ta. calle sobre la 5ta. avenida zona 2',
      tipo: 'regreso',
      lat: 14.64982,
      lng: -90.512743,
      piezas: [
        { nombre: 'Corpus Meum', autor: 'José Luis Gónzalez' },
        { nombre: 'Amanecer', autor: 'Lester Homero Godínez' },
      ],
    },
    {
      label: 'Turno 64',
      direccion: 'De la 5ta. avenida a la Avenida Simeón Cañas sobre la 5ta. calle zona 2',
      tipo: 'regreso',
      lat: 14.648106,
      lng: -90.512743,
      piezas: [
        { nombre: 'Reina de Reyes', autor: 'Alejandro Blanco' },
        { nombre: 'Reina Celestial', autor: 'Fredy Sajmolo' },
      ],
    },
    {
      label: 'Extraordinario Jocotenango 1',
      direccion: 'De la 5ta. calle a la 3era. calle sobre la Avenida Simeón Cañas zona 2',
      tipo: 'regreso',
      lat: 14.648106,
      lng: -90.511616,
      piezas: [
        { nombre: 'Noche de Luna Entre Ruinas', autor: 'Mariano Valverde' },
        { nombre: 'La Despedida', autor: 'Oscar Ajin' },
      ],
    },
    {
      label: 'Turno 66',
      direccion: 'De la Avenida Simeón Cañas a la 6ta. avenida A sobre la 3era. calle zona 2',
      tipo: 'regreso',
      lat: 14.64982,
      lng: -90.511616,
      piezas: [
        { nombre: 'Vals No. 2', autor: 'Dimitri Shostakovich' },
      ],
    },
    {
      label: 'Extraordinario Jocotenango 2',
      direccion: 'De la 3era. calle a la 5ta. calle sobre la 6ta. avenida A zona 2',
      tipo: 'regreso',
      lat: 14.64982,
      lng: -90.512743,
      piezas: [
        { nombre: 'Vuela Quetzal, Vuela', autor: 'Oscar Ajín' },
        { nombre: 'La Esperanza de María', autor: 'Alejandro Blanco' },
      ],
    },
    {
      label: 'Turno 68',
      direccion: 'De la 6ta. avenida A a la Avenida Simeón Cañas sobre la 5ta. calle zona 2',
      tipo: 'regreso',
      lat: 14.650677,
      lng: -90.512743,
      piezas: [
        { nombre: 'Señora y Niña Mía', autor: 'Cristian González Ajín' },
      ],
    },
    {
      label: 'Turno 69',
      direccion: 'De la 5ta. calle a la 6ta. calle sobre la Avenida Simeón Cañas zona 2',
      tipo: 'regreso',
      lat: 14.651534,
      lng: -90.512743,
      piezas: [
        { nombre: 'Bajo el cielo azul', autor: 'Froilán Rodas Santizo' },
        { nombre: 'El Carpintero', autor: 'Antonio Mendoza' },
      ],
    },
    {
      label: 'Turno 70',
      direccion: 'De la 6ta. calle a la 7ma. calle sobre la Avenida Simeón Cañas zona 2',
      tipo: 'regreso',
      lat: 14.651534,
      lng: -90.51049,
      piezas: [
        { nombre: 'Vamos torito a bailar', autor: 'Marvin Escobar' },
        { nombre: 'Blanca Azucena', autor: 'Miguel Gómez' },
      ],
    },
    {
      label: 'Turno 71',
      direccion: 'De la Avenida Simeón Cañas a la 7ma. avenida sobre la 7ma. calle zona 2',
      tipo: 'regreso',
      lat: 14.650677,
      lng: -90.51049,
      piezas: [
        { nombre: 'Alejandra', autor: 'Enrique Mora' },
      ],
    },
    {
      label: 'Turno 72',
      direccion: 'De la 7ma. calle a la 6ta. calle sobre la 7ma. avenida zona 2',
      tipo: 'regreso',
      lat: 14.64993,
      lng: -90.51049,
      piezas: [
        { nombre: 'Noche Buena', autor: 'Salvador Iriarte' },
      ],
    },
    {
      label: 'Honor Entrada',
      direccion: 'De la 6ta. calle y 7ma. avenida zona 2 al dosel del templo',
      tipo: 'regreso',
      lat: 14.64993,
      lng: -90.51049,
      piezas: [
        { nombre: 'La Danza de los Venados', autor: 'Rafael Juárez Toledo' },
        { nombre: 'La Quema del Diablo', autor: 'Rafael Juárez Toledo' },
        { nombre: 'La Granadera', autor: 'D.R.A' },
        { nombre: 'Salve, Nuestra Señora', autor: 'Yarol Cur / Arre. Pablo Daniel Díaz' },
        { nombre: 'Himno de la Asunción', autor: 'José Cubeles/Arr. Luis Pirir' },
        { nombre: 'Toritos', autor: null },
        { nombre: 'Cuando cae la lluvia', autor: null },
        { nombre: 'Mi Lupita', autor: null },
        { nombre: 'Toritos Concepción Tutuapa', autor: null },
        { nombre: 'Colonia Montreal', autor: null },
        { nombre: 'Maricumbia', autor: null },
        { nombre: 'Chichicastenango', autor: null },
      ],
    },
  ],
}
